name: Pipeline DevSecOps PHP

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  # 🔐 Scan des secrets (TruffleHog)
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Scan secrets with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .          
          
  # 🧹 Linter PHP (PHPCS)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PHPCS
        run: composer global require squizlabs/php_codesniffer

      - name: Run PHPCS (PSR-12)
        run: ~/.composer/vendor/bin/phpcs src --standard=PSR12

  # 🔍 SAST (Semgrep)
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

  # 📦 SCA (Trivy filesystem)
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table

  # 🐳 Scan image Docker (Trivy Image)
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-php-app ./src

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-php-app
          format: table

  # 🌐 DAST (OWASP ZAP)
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start PHP server
        run: |
          php -S localhost:8000 -t src &
          sleep 5

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:8000"